name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn lint
      - run: yarn test-ci
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
